export const tempCategories = [
    "Electronics",
    "Furniture",
    "Home Decor",
    "Appliances",
    "Kitchen & Dining",
    "Home & Garden",
    "Tools & Hardware",
    "Sporting Goods",
    "Outdoor & Camping",
    "Bicycles",
    "Automotive",
    "Motorcycles & Scooters",
    "Parts & Accessories",
    "Baby & Kids",
    "Toys & Games",
    "Video Games & Consoles",
    "Computers & Laptops",
    "Phones & Tablets",
    "TVs & Audio",
    "Cameras & Photography",
    "Musical Instruments",
    "Books",
    "Movies & Music",
    "Clothing",
    "Shoes",
    "Jewelry & Watches",
    "Beauty & Personal Care",
    "Health & Fitness",
    "Pet Supplies",
    "Art & Collectibles",
    "Crafts & Hobbies",
    "Office Supplies",
    "Business & Industrial",
    "Tickets",
    "Free Stuff",
    "Services",
    "Handmade",
    "Seasonal",
    "Antiques",
    "Real Estate",
    "Rentals",
    "Jobs",
    "Farm & Garden",
    "Party Supplies",
    "Travel & Luggage",
 ] 